package net.astechdesign.clients.repo;

import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;

import javax.sql.DataSource;
import java.sql.*;

public class DBBuilder {

    private static String[] TABLE_NAMES = {"PRODUCTS", "CONTACTS", "ORDERS", "TODOS"};

    public static void initialiseDb(DataSource dataSource) {
        QueryRunner queryRunner = new QueryRunner(dataSource);
        try {
            Boolean isInitialised = queryRunner.query("select * from dbInit", new ResultSetHandler<Boolean>() {
                @Override
                public Boolean handle(ResultSet rs) throws SQLException {
                    rs.next();
                    return rs.getBoolean(1);
                }
            });
            if (isInitialised) return;
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            buildTables(queryRunner);
            TestContactsRepo.init();
            queryRunner.update("insert into dbInit values('true')");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void buildTables(QueryRunner runner) throws SQLException {
        for (String name : TABLE_NAMES) {
            runner.update("CREATE SEQUENCE " + name + "_SEQ;");
        }

        runner.update("CREATE TEXT TABLE products(" +
                "id INT GENERATED BY DEFAULT AS SEQUENCE PRODUCTS_SEQ PRIMARY KEY," +
                "code VARCHAR(25)," +
                "name VARCHAR(100)," +
                "price VARCHAR(8)," +
                "createDate DATE DEFAULT CURRENT_DATE" +
                ")");

        runner.update("CREATE TEXT TABLE contacts(" +
                "id INT GENERATED BY DEFAULT AS SEQUENCE CONTACTS_SEQ PRIMARY KEY," +
                "name VARCHAR(75)," +
                "address VARCHAR(200)," +
                "postcode VARCHAR(10)," +
                "telephone VARCHAR(15)," +
                "createDate DATE DEFAULT CURRENT_DATE" +
                ")");

        runner.update("CREATE TEXT TABLE orders(" +
                "id INT GENERATED BY DEFAULT AS SEQUENCE ORDERS_SEQ PRIMARY KEY," +
                "contactId INT," +
                "productId INT," +
                "deliveryDate DATE DEFAULT CURRENT_DATE," +
                "amount INT," +
                "createDate DATE DEFAULT CURRENT_DATE" +
                ")");

        runner.update("CREATE TEXT TABLE todos(" +
                "id INT GENERATED BY DEFAULT AS SEQUENCE TODOS_SEQ PRIMARY KEY," +
                "contactId INT," +
                "date DATE," +
                "notes VARCHAR(500)," +
                "createDate DATE DEFAULT CURRENT_DATE" +
                ")");

        runner.update("CREATE TEXT TABLE dbInit(init BOOLEAN)");

        for (String name : TABLE_NAMES) {
            runner.update("SET TABLE " + name + " SOURCE \"" + name + "\"");
        }
        runner.update("SET TABLE dbInit SOURCE \"dbInit\"");
    }
}