package net.astechdesign.clients.repo;

import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;

import javax.sql.DataSource;
import java.io.IOException;
import java.net.URL;
import java.sql.*;

public class DBBuilder {

    private static String[] SEQUENCE_NAMES = {"CONTACT", "ORDER", "CATEGORY", "TODO"};

    public static void initialiseDb(DataSource dataSource) {
        try {
            scripted(dataSource);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) throws IOException {
        loader(null);
    }

    public static void loader(DataSource dataSource) throws IOException {
        URL resource = Thread.currentThread().getContextClassLoader().getResource("db");
        Tables tables = new Tables(resource);

        for (Table table : tables.get()) {

        }


        QueryRunner queryRunner = new QueryRunner(dataSource);
        try {
            Boolean isInitialised = queryRunner.query("select * from dbInit", new ResultSetHandler<Boolean>() {
                @Override
                public Boolean handle(ResultSet rs) throws SQLException {
                    rs.next();
                    return rs.getBoolean(1);
                }
            });
            if (isInitialised) return;
        } catch (Exception e) {
//            e.printStackTrace();
        }

    }

    public static void scripted(DataSource dataSource) throws SQLException {
        Connection conn = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost:9001/Contacts", "SA", "");
        Statement statement = conn.createStatement();
        for (String name : SEQUENCE_NAMES) {
            statement.execute("CREATE SEQUENCE " + name + "_SEQ;");
        }

        statement.execute("CREATE TABLE contacts(" +
                "id INT GENERATED BY DEFAULT AS SEQUENCE CONTACT_SEQ PRIMARY KEY," +
                "first VARCHAR(25)," +
                "last VARCHAR(50)," +
                "number INT," +
                "houseName VARCHAR(20)," +
                "address1 VARCHAR(60)," +
                "town VARCHAR(30)," +
                "county VARCHAR(20)," +
                "postcode VARCHAR(10)," +
                "telephone VARCHAR(15)" +
                ")");

        statement.execute("CREATE TABLE orders(" +
                "id INT GENERATED BY DEFAULT AS SEQUENCE ORDER_SEQ PRIMARY KEY," +
                "contactId INT," +
                "year INT," +
                "month INT," +
                "day INT," +
                "amount INT," +
                "productId INT" +
                ")");

        statement.execute("CREATE TABLE products(" +
                "id INT PRIMARY KEY," +
                "categoryId INT," +
                "name VARCHAR(100)," +
                "description VARCHAR(450)" +
                ")");


        statement.execute("CREATE TABLE todos(" +
                "id INT GENERATED BY DEFAULT AS SEQUENCE TODO_SEQ PRIMARY KEY," +
                "contactId INT," +
                "start DATE," +
                "end DATE," +
                "notes VARCHAR(500)" +
                ")");

        statement.execute("CREATE TABLE dbInit(init BOOLEAN)");
        statement.execute("insert into dbInit values('true')");

        statement.close();
        conn.commit();
    }

    public static void scripted2(DataSource dataSource) {
        QueryRunner queryRunner = new QueryRunner(dataSource);
        try {
            Boolean isInitialised = queryRunner.query("select * from dbInit", new ResultSetHandler<Boolean>() {
                @Override
                public Boolean handle(ResultSet rs) throws SQLException {
                    rs.next();
                    return rs.getBoolean(1);
                }
            });
            if (isInitialised) return;
        } catch (Exception e) {
//            e.printStackTrace();
        }
        try {
            for (String name : SEQUENCE_NAMES) {

                queryRunner.update("CREATE SEQUENCE " + name + "_SEQ;");
            }

            queryRunner.update("CREATE TABLE contacts(" +
                    "id INT GENERATED BY DEFAULT AS SEQUENCE CONTACT_SEQ PRIMARY KEY," +
                    "first VARCHAR(25)," +
                    "last VARCHAR(50)," +
                    "number INT," +
                    "houseName VARCHAR(20)," +
                    "address1 VARCHAR(60)," +
                    "town VARCHAR(30)," +
                    "county VARCHAR(20)," +
                    "postcode VARCHAR(10)," +
                    "telephone VARCHAR(15)" +
                    ")");

            queryRunner.update("CREATE TABLE orders(" +
                    "id INT GENERATED BY DEFAULT AS SEQUENCE ORDER_SEQ PRIMARY KEY," +
                    "contactId INT," +
                    "year INT," +
                    "month INT," +
                    "day INT," +
                    "amount INT," +
                    "productId INT" +
                    ")");

            queryRunner.update("CREATE TABLE products(" +
                    "id INT PRIMARY KEY," +
                    "categoryId INT," +
                    "name VARCHAR(100)," +
                    "description VARCHAR(450)" +
                    ")");


            queryRunner.update("CREATE TABLE todos(" +
                    "id INT GENERATED BY DEFAULT AS SEQUENCE TODO_SEQ PRIMARY KEY," +
                    "contactId INT," +
                    "start DATE," +
                    "end DATE," +
                    "notes VARCHAR(500)" +
                    ")");

            queryRunner.update("CREATE TABLE dbInit(init BOOLEAN)");
            queryRunner.update("insert into dbInit values('true')");
        } catch (Exception e) {
            throw new RuntimeException("", e);
        }
    }


}