package net.astechdesign.clients.repo;

import com.google.common.collect.Lists;

import java.util.ArrayList;
import java.util.List;

public class Table {

    private String sequence;
    private List<Field> fields = Lists.newArrayList();

    public Table(String tableName, List<String> tableConfig) {
        for (String fieldDef : tableConfig) {
            Field field = new Field(tableName, true, fieldDef.split(":"));
            if (field.isSequence()) {
                sequence = "";
            }
            fields.add(field);
        }
    }

    public Table(ArrayList<String> tableConfig) {
        this("name", tableConfig);
    }

    public String create() {
        return null;
    }

    public String sequence() {
        return null;
    }

    /*
           tableConfig.add("id:INT:SEQ");
        tableConfig.add("categoryId:INT");
        tableConfig.add("name:100");
        tableConfig.add("description:450");

       assertThat(table.sequence(), is("CREATE SEQUENCE PRODUCTS_SEQ"));
        assertThat(table.create(),
                is("CREATE TABLE products(" +
                   "id INT GENERATED BY DEFAULT AS SEQUENCE CONTACT_SEQ PRIMARY KEY," +
                   "categoryId INT," +
                   "name VARCHAR(100)," +
                   "description VARCHAR(450))"));

     */
}
