package net.astechdesign.contacts.repo;

import org.apache.commons.dbutils.QueryRunner;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

public class DBBuilder {

    public static void initialiseDb(DataSource dataSource) {
        try {
            QueryRunner queryRunner = new QueryRunner(dataSource);

            queryRunner.update("CREATE SEQUENCE CONTACT_SEQ");
            queryRunner.update("CREATE TABLE contacts(" +
                    "id INT GENERATED BY DEFAULT AS SEQUENCE CONTACT_SEQ PRIMARY KEY," +
                    "first VARCHAR(25)," +
                    "last VARCHAR(50)," +
                    "number INT," +
                    "houseName VARCHAR(20)," +
                    "address1 VARCHAR(60)," +
                    "town VARCHAR(30)," +
                    "county VARCHAR(20)," +
                    "postcode VARCHAR(10)," +
                    "telephone VARCHAR(15)" +
                    ")");

            queryRunner.update("CREATE SEQUENCE ORDER_SEQ");
            queryRunner.update("CREATE TABLE orders(" +
                    "id INT GENERATED BY DEFAULT AS SEQUENCE ORDER_SEQ PRIMARY KEY," +
                    "contactId INT," +
                    "year INT," +
                    "month INT," +
                    "day INT," +
                    "amount INT," +
                    "productId INT" +
                    ")");

            queryRunner.update("CREATE TABLE products(" +
                    "id INT PRIMARY KEY," +
                    "categoryId INT," +
                    "name VARCHAR(25)," +
                    "description VARCHAR(50)" +
                    ")");

            queryRunner.update("CREATE TABLE categories(" +
                    "id INT PRIMARY KEY," +
                    "category VARCHAR(25)" +
                    ")");

            queryRunner.update("CREATE TABLE dbInit(init BOOLEAN)");
            queryRunner.update("insert into dbInit values('true')");
        } catch (Exception e) {
            throw new RuntimeException("", e);
        }
    }


}