package net.astechdesign.contacts.repo;


import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class FieldTest {

    @Test
    public void constructor_primaryKey() throws Exception {
        Field field = new Field("contact", true, new String[]{"id", "INT", "SEQ"});
        assertThat(field.toString(), is("id INT GENERATED BY DEFAULT AS SEQUENCE CONTACT_SEQ PRIMARY KEY"));
    }
}