package net.astechdesign.contacts.repo;

import com.google.common.collect.Lists;
import org.junit.Test;

import java.util.ArrayList;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class TableTest {

    @Test
    public void constructor() throws Exception {
        ArrayList<String> tableConfig = Lists.newArrayList();
        tableConfig.add("id:INT:SEQ");
        tableConfig.add("categoryId:INT");
        tableConfig.add("name:100");
        tableConfig.add("description:450");

        Table table = new Table(tableConfig);

        assertThat(table.sequence(), is("CREATE SEQUENCE PRODUCTS_SEQ"));
        assertThat(table.create(),
                is("CREATE TABLE products(" +
                   "id INT GENERATED BY DEFAULT AS SEQUENCE CONTACT_SEQ PRIMARY KEY," +
                   "categoryId INT," +
                   "name VARCHAR(100)," +
                   "description VARCHAR(450))"));
    }
}